---
title: "CodeToqunatifyOrganoidImages_new_mCol_Revision"
author: "Saskia Reuter"
date: "2024-07-23"
output: html_document
df_print: paged
toc: yes
toc_depth: 3
toc_float:
collapsed: no
smooth_scroll: yes
pdf_document: default
number_sections: no
highlight: tango
theme: default
---


*Last modified:*
```{r}
print(date())
```

#Load packages
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("EBImage")
library(EBImage)
library(tidyverse)

```

*Quantify Organoid number, area and radius using Image Masks generated by Cellpose*
*Data Revision*
#R1-Revision
```{r}
# where are your image masks
mask_folder <- "~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Masks_R1_rev_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features1R <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features1R)) # number organoids in that image
  area_org <- append(area_org, sum(features1R$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features1R$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data1R <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta1R <- (read.csv("~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Overview_ImageNr_WellContent_RevisionR1.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R1_rev")
organoid_data1R <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data1R <-full_join(organoid_data1R, meta1R, by="ImageNr")
```

#R2-Revision
```{r}
# where are your image masks
mask_folder <- "~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Masks_R2_rev_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features2R <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features2R)) # number organoids in that image
  area_org <- append(area_org, sum(features2R$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features2R$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data2R <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta2R <- (read.csv("~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Overview_ImageNr_WellContent_RevisionR2-R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R2_rev")
organoid_data2R <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data2R <- full_join(organoid_data2R, meta2R, by="ImageNr")
```

#R3-Revision
```{r}
# where are your image masks
mask_folder <- "~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Masks_R3_rev_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features3R <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features3R)) # number organoids in that image
  area_org <- append(area_org, sum(features3R$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features3R$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data3R <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta3R <- (read.csv("~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Overview_ImageNr_WellContent_RevisionR2-R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R3_rev")
organoid_data3R <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data3R <- full_join(organoid_data3R, meta3R, by="ImageNr")
```

#R4-Revision
```{r}
# where are your image masks
mask_folder <- "~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Masks_R4_rev_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features4R <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features4R)) # number organoids in that image
  area_org <- append(area_org, sum(features4R$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features4R$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data4R <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta4R <- (read.csv("~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Overview_ImageNr_WellContent_RevisionR2-R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R4_rev")
organoid_data4R <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data4R <- full_join(organoid_data4R, meta4R, by="ImageNr")
```

#R5-Revision
```{r}
# where are your image masks
mask_folder <- "~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Masks_R5_rev_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features5R <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features5R)) # number organoids in that image
  area_org <- append(area_org, sum(features5R$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features5R$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data5R <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta5R <- (read.csv("~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/raw_data/ImageMasks_RevisionR1-R5/Overview_ImageNr_WellContent_RevisionR2-R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R5_rev")
organoid_data5R <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data5R <- full_join(organoid_data5R, meta5R, by="ImageNr")
```

#Combine all data of Revision in one table and export as TSV
```{r}
ImageQuantification_Revision_results <- rbind(organoid_data1R, organoid_data2R, organoid_data3R, organoid_data4R, organoid_data5R)
write.table(ImageQuantification_Revision_results, file="~/Nextcloud/Saskia&Kim/Experiments_JNK_mCOL_APC/Final_Data_Paper_Revision/Code_Image_Data_for_Git/results/ImageQuantification_Revision_results.tsv")
```


#Sessioninfo
```{r}
sessionInfo()
```