---
title: "CodeToqunatifyOrganoidImages_new_mCol"
author: "Saskia Reuter"
date: "2025-02-10"
output: html_document
df_print: paged
toc: yes
toc_depth: 3
toc_float:
collapsed: no
smooth_scroll: yes
pdf_document: default
number_sections: no
highlight: tango
theme: default
---

*Last modified:*
```{r}
print(date())
```

#Load packages
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("EBImage")
library(EBImage)
library(tidyverse)
```

*Quantify Organoid number, area and radius using Image Masks generated by Cellpose*
#R1
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R1_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features1 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features1)) # number organoids in that image
  area_org <- append(area_org, sum(features1$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features1$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data1 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta1 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R1,R3,R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R1")
organoid_data1 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data1 <-full_join(organoid_data1, meta1, by="ImageNr")
```

#R2
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R2_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features2 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features2)) # number organoids in that image
  area_org <- append(area_org, sum(features2$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features2$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data2 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta2 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R2,R4,R6.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R2")
organoid_data2 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data2 <-full_join(organoid_data2, meta2, by="ImageNr")
```

#R3
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R3_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features3 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features3)) # number organoids in that image
  area_org <- append(area_org, sum(features3$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features3$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data3 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta3 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R1,R3,R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R3")
organoid_data3 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data3 <-full_join(organoid_data3, meta3, by="ImageNr")
```

#R4
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R4_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features4 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features4)) # number organoids in that image
  area_org <- append(area_org, sum(features4$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features4$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data4 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta4 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R2,R4,R6.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R4")
organoid_data4 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data4 <-full_join(organoid_data4, meta4, by="ImageNr")
```

#R5
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R5_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features5 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features5)) # number organoids in that image
  area_org <- append(area_org, sum(features5$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features5$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data5 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta5 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R1,R3,R5.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R5")
organoid_data5 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data5 <-full_join(organoid_data5, meta5, by="ImageNr")
```

#R6
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R6_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features6 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features6)) # number organoids in that image
  area_org <- append(area_org, sum(features6$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features6$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data6 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta6 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R2,R4,R6.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R6")
organoid_data6 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data6 <-full_join(organoid_data6, meta6, by="ImageNr")
```

#R8
```{r}
# where are your image masks
mask_folder <- "~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Masks_R8_new"

# listing all masks in the folder
mask_list <- list.files(mask_folder, pattern = ".tif")
# making empty vectors
n_org <- c()
area_org <- c()
radius_mean <- c()
# running for loop over all mask images
for (i in mask_list){
  mask <- readImage(paste0(mask_folder, "/", i), as.is = T)
  features8 <- as.data.frame(computeFeatures(x = mask,ref = mask,methods.ref = c("computeFeatures.shape")))
  # you'll receive a bunch of features, you said you were interested in number of organoids and organoid area
  n_org <- append(n_org ,nrow(features8)) # number organoids in that image
  area_org <- append(area_org, sum(features8$x.0.s.area)) # number of pixels covered by organoid in that image
  radius_mean <- append(radius_mean, mean(features8$x.0.s.radius.mean))
}
# making data frame and matching ImageNumber to well content
organoid_data8 <- data.frame(image_name = mask_list, n_org, area_org, radius_mean)
meta8 <- (read.csv("~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/raw_data/ImageMasks_R1-R8/Overview_ImageNr_WellContent_R8.csv", header = TRUE, sep=";"))

ImageNr <- gsub(".*_(XY[0-9]+)_.*", "\\1", mask_list)
Replicate <- c("R8")
organoid_data8 <- data.frame(ImageNr, n_org, area_org, radius_mean, Replicate)
organoid_data8 <-full_join(organoid_data8, meta8, by="ImageNr")
```


#Combine all data in one table and export as TSV
```{r}
ImageQuantification_R1toR8_results <- rbind(organoid_data1, organoid_data2, organoid_data3, organoid_data4, organoid_data5, organoid_data6, organoid_data8)
write.table(ImageQuantification_R1toR8_results, file="~/GitHub/Supp_Redhai_Wang_2023/Image_Analysis/Results/ImageQuantification_R1toR8_results.tsv")
```

#Sessioninfo
```{r}
sessionInfo()
```
